// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwhonfEebZNQPG_WbKFp_hb0ULXM5Ex8g',
    appId: '1:1039636867285:android:361a64356ef862a3591a5c',
    messagingSenderId: '1039636867285',
    projectId: 'nanochat-e9b21',
    storageBucket: 'nanochat-e9b21.appspot.com'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj6iw-krNsDjBslrxWIiQAkM6p6jYsoes',
    iosBundleId: 'com.mobile.nanochat',
    appId: '1:1039636867285:ios:549bc6fa392ede3f591a5c',
    storageBucket: 'nanochat-e9b21.appspot.com',
    messagingSenderId: '1039636867285',
    iosClientId: 'undefined',
    projectId: 'nanochat-e9b21'
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAhE5iTdU1MflQxb4_M_uHiXJR9EC_mE_I",
      authDomain: "nanochat.firebaseapp.com",
      projectId: "firebase-nanochat",
      messagingSenderId: '137230848633',
      appId: '1:137230848633:web:89e9b54f881fa0b843baa8');
}
